#!/usr/bin/env python3
"""Generate an EXP-7 sweep config JSON for `sjs_sweep`.

EXP-7 (Phase Breakdown & explanatory profiling) runs small sweeps on a few
representative density points (alpha) and then post-processes `phases_json`
into a phase breakdown table + (optionally) stacked-bar plots.

This helper writes a standalone sweep config consumed by `sjs_sweep`.

Why this exists:
  - Repo-wide convention: bash runners contain *no* embedded Python.
  - JSON configs generated by runners should live under `run/temp/...`.

The produced JSON matches the repo's sweep schema used by `sjs_sweep`.
"""

from __future__ import annotations

import argparse
import json
import os
from typing import Any, Dict, List


DEFAULT_METHODS = (
    "ours aabb interval_tree kd_tree r_tree range_tree pbsm tlsop sirs rejection tsunami"
)


def _split_tokens(s: str) -> List[str]:
    """Split a list-like string by comma and/or whitespace."""
    parts: List[str] = []
    for tok in s.replace(",", " ").split():
        tok = tok.strip()
        if tok:
            parts.append(tok)
    return parts


def _parse_alphas(s: str) -> List[float]:
    out: List[float] = []
    for tok in _split_tokens(s):
        try:
            out.append(float(tok))
        except ValueError as e:
            raise SystemExit(f"[EXP7][ERROR] Bad alpha token '{tok}' in --alphas: {e}")
    return out


def main() -> int:
    ap = argparse.ArgumentParser(
        description="EXP-7 helper: generate a sweep config JSON for sjs_sweep"
    )

    ap.add_argument("--out", required=True, help="Path to write the sweep config JSON")
    ap.add_argument(
        "--out_dir",
        required=True,
        help="Output directory to set as base.output.out_dir (sweep artifacts land here)",
    )
    ap.add_argument("--run_tag", required=True, help="base.output.run_tag")
    ap.add_argument(
        "--note",
        default="",
        help="Optional meta.note written into the config (for provenance)",
    )

    # Dataset & run defaults align with EXP-7.md
    ap.add_argument("--nr", type=int, default=100000)
    ap.add_argument("--ns", type=int, default=100000)
    ap.add_argument("--t", type=int, default=100000)
    ap.add_argument("--repeats", type=int, default=3)
    ap.add_argument("--gen_seed", type=int, default=1)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--threads", type=int, default=1)
    ap.add_argument("--j_star", type=int, default=1000000)
    ap.add_argument("--enum_cap", type=int, default=0)

    ap.add_argument(
        "--alphas",
        type=str,
        default="0.1 3 30",
        help="Representative alpha points (comma/space-separated). Example: '0.1 3 30'",
    )
    ap.add_argument(
        "--methods",
        type=str,
        default=DEFAULT_METHODS,
        help="Methods to sweep (comma/space-separated)",
    )
    ap.add_argument(
        "--variants",
        type=str,
        required=True,
        help="Variants to sweep (comma/space-separated). Example: 'sampling adaptive'",
    )

    args = ap.parse_args()

    alphas = _parse_alphas(args.alphas)
    if not alphas:
        raise SystemExit("[EXP7][ERROR] --alphas must contain at least one value")

    methods = _split_tokens(args.methods)
    if not methods:
        raise SystemExit("[EXP7][ERROR] --methods must contain at least one method")

    variants = _split_tokens(args.variants)
    if not variants:
        raise SystemExit("[EXP7][ERROR] --variants must contain at least one variant")

    out_dir = os.path.abspath(args.out_dir)
    out_path = os.path.abspath(args.out)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    os.makedirs(out_dir, exist_ok=True)

    # Keep generator params explicit to match EXP-7.md (stripe_ctrl_alpha).
    cfg: Dict[str, Any] = {
        "base": {
            "dataset": {
                "source": "synthetic",
                "name": "exp7_stripe",
                "dim": 2,
                "synthetic": {
                    "generator": "stripe_ctrl_alpha",
                    "n_r": int(args.nr),
                    "n_s": int(args.ns),
                    # alpha is swept; seed/params are fixed.
                    "alpha": float(alphas[0]),
                    "seed": int(args.gen_seed),
                    "params": {
                        "control_axis": 1,
                        "core_lo": 0.45,
                        "core_hi": 0.55,
                        "gap_factor": 0.1,
                        "delta_factor": 0.25,
                        "shuffle_strips": True,
                        "shuffle_r": False,
                        "swap_sides": False,
                    },
                },
            },
            "run": {
                "method": "ours",
                "variant": variants[0],
                "t": int(args.t),
                "seed": int(args.seed),
                "repeats": int(args.repeats),
                "j_star": int(args.j_star),
                "enum_cap": int(args.enum_cap),
                "write_samples": False,
                "verify": False,
                "extra": {
                    "pbsm_scheme": "stripes",
                    "pbsm_k": 0,
                    "pbsm_part_axis": 0,
                    "pbsm_sweep": "orthogonal",
                    "tlsop_nx": 128,
                    "tlsop_ny": 128,
                    "tlsop_reuse_sort": True,
                    "sirs_outer": "",
                    "sirs_leaf_size": 32,
                    "rej_index": "S",
                    "rej_rep_center": False,
                    "rej_count_draws": 50000,
                    "rej_max_factor": 10000,
                },
            },
            "output": {
                "out_dir": out_dir,
                "run_tag": str(args.run_tag),
            },
            "logging": {
                "level": "info",
                "with_timestamp": True,
                "with_thread_id": False,
            },
            "sys": {"threads": int(args.threads)},
        },
        "sweep": {
            "alpha": alphas,
            "method": methods,
            "variant": variants,
        },
        "files": {
            "raw": "sweep_raw.csv",
            "summary": "sweep_summary.csv",
        },
        "meta": {
            "note": str(args.note),
        },
    }

    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=2, ensure_ascii=False)

    print(f"[EXP7] Wrote sweep config: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
